### PR TITLE
Use Chandra.Time instead of mx.DateTime

### PR DESCRIPTION
**Pull request by jeanconn**
Use Chandra.Time instead of mx.DateTime

### CODE REVIEW

**Comment by jeanconn** [comment]
I couldn't figure out a back-compatible approach to this transition here, so I just updated the scripts that call this package and have each to wrap the 'start' and 'stop' times in Chandra.Time.DateTime(), so those scripts are back compatible even if this package is not.

**Comment by taldcroft** [comment]
What is not back-compatible about this PR?

**Comment by jeanconn** [comment]
Some of the methods now return dicts with values as Chandra.Time.DateTime
objects instead of mx.DateTime objects.

**Comment by taldcroft** [comment]
OK.  I guess any scripts that call this and are still expecting an `mx.DateTime` object will fail quickly and not accidentally keep going and give wrong results?

**Comment by jeanconn** [comment]
I'm not actually confident about that,  as we've got overlap in their
attribute names,  but there is nothing critical using this package and I
think I've updated all of the things calling it.

**Pull request merged**
